const colors = {
  white: "#ffffff",
  black: "#000000",
  grey_0: "#d5d5d5",
  grey_1: "#a6a6a6",
  grey_2: "#777",
  red: "#e84118",
  blue: "#3679fe",
  beige: "#cc9A73",
};

export const theme = {
  background: colors.white,
  text: colors.black,
  imageBackground: colors.grey_0,
  label: colors.grey_1,
  inputPlaceholder: colors.grey_1,
  inputBorder: colors.grey_1,
  errorText: colors.red,
  buttonBackground: colors.beige,
  buttonTitle: colors.white,
  buttonUnfilledTitle: colors.beige,
  headerTintColor: colors.black,
  ImageButtonBackground: colors.grey_2,
  ImageButtonIcon: colors.white,
  spinnerBackground: colors.black,
  spinnerIndicator: colors.white,
  tabActiveColor: colors.beige,
  tabInacitveColor: colors.grey_1,
};
